# Data Cleaning and Aggregation

In [2]:
import numpy as np
import pandas as pd

In [3]:
# Load Dataset

df = pd.read_csv("C:\\Users\\Administrator\\Downloads\\Bank_Loan_Portfolio.csv")
print("\nCSV Data:\n", df.head())

CSV Data:
     Loan_ID Application_Date       City Region  Age Employment_Type    Income  \
0  LN102453       2023-08-13     Mumbai   West   43   Self-Employed   90322.0
1  LN100671       2024-11-26  Hyderabad  South   28        Salaried   32617.0
2  LN100884       2024-03-07     Mumbai   West   34        Business   86468.0
3  LN100618       2023-04-07     Mumbai   West   33   Self-Employed  110760.0
4  LN100344       2023-05-30     Mumbai   West   37        Salaried  141338.0

   Loan_Amount  Loan_Tenure_Months  Interest_Rate_Percent  Credit_Score  \
0     980052.0                  84                  10.92         672.0
1     488350.0                  54                   9.99         698.0
2          NaN                  53                  11.56         709.0
3    1298938.0                  59                   8.36         730.0
4    1627058.0                 110                  10.14         767.0

   Debt_To_Income_Ratio Approval_Status  Default_Flag Loan_Status  \
0                 0.185        Approved             0      Active
1                 0.345        Approved             0        Paid
2                 0.422        Rejected             0    Rejected
3                 0.243        Approved             0      Active
4                 0.161        Approved             0      Active

   Customer_Rating Risk_Category
0              4.1        Medium
1              4.6        Medium
2              4.4        Medium
3              5.0           Low
4              4.5           Low

In [4]:
df.head()

,Loan_ID,Application_Date,City,Region,Age,Employment_Type,Income,Loan_Amount,Loan_Tenure_Months,Interest_Rate_Percent,Credit_Score,Debt_To_Income_Ratio,Approval_Status,Default_Flag,Loan_Status,Customer_Rating,Risk_Category
0,LN102453,2023-08-13,Mumbai,West,43,Self-Employed,90322.0,980052.0,84,10.92,672.0,0.185,Approved,0,Active,4.1,Medium
1,LN100671,2024-11-26,Hyderabad,South,28,Salaried,32617.0,488350.0,54,9.99,698.0,0.345,Approved,0,Paid,4.6,Medium
2,LN100884,2024-03-07,Mumbai,West,34,Business,86468.0,NaN,53,11.56,709.0,0.422,Rejected,0,Rejected,4.4,Medium
3,LN100618,2023-04-07,Mumbai,West,33,Self-Employed,110760.0,1298938.0,59,8.36,730.0,0.243,Approved,0,Active,5.0,Low
4,LN100344,2023-05-30,Mumbai,West,37,Salaried,141338.0,1627058.0,110,10.14,767.0,0.161,Approved,0,Active,4.5,Low

In [5]:
df.sample(5)

,Loan_ID,Application_Date,City,Region,Age,Employment_Type,Income,Loan_Amount,Loan_Tenure_Months,Interest_Rate_Percent,Credit_Score,Debt_To_Income_Ratio,Approval_Status,Default_Flag,Loan_Status,Customer_Rating,Risk_Category
429,LN102375,2024-06-05,Pune,West,38,Salaried,85894.0,3.276063e+06,81,11.07,695.0,0.199,Approved,0,Paid,4.3,Medium
2096,LN101965,2023-04-19,Pune,West,39,Salaried,127464.0,1.354476e+06,77,11.00,713.0,0.193,Approved,0,Active,4.5,Medium
1592,LN100561,2024-12-26,Delhi,North,37,Salaried,82581.0,NaN,72,10.76,680.0,0.103,Approved,0,Active,4.3,Medium
865,LN100429,2024-01-06,Mumbai,West,44,Business,111545.0,1.097022e+06,82,13.00,691.0,0.182,Rejected,0,Rejected,4.8,Medium
675,LN101567,2024-06-20,Delhi,North,34,Salaried,144326.0,1.295145e+06,97,10.10,756.0,0.136,Approved,0,Paid,4.4,Low

In [6]:
# Checking shape of the dataframe

df.shape

(3000, 17)

In [7]:
# Checking datatypes of all columns in the dataframe

df.dtypes

Loan_ID                   object
Application_Date          object
City                      object
Region                    object
Age                        int64
Employment_Type           object
Income                   float64
Loan_Amount              float64
Loan_Tenure_Months         int64
Interest_Rate_Percent    float64
Credit_Score             float64
Debt_To_Income_Ratio     float64
Approval_Status           object
Default_Flag               int64
Loan_Status               object
Customer_Rating          float64
Risk_Category             object
dtype: object

In [8]:
# checking null values of all columns

df.isnull().sum()

Loan_ID                    0
Application_Date           0
City                       0
Region                     0
Age                        0
Employment_Type          120
Income                   120
Loan_Amount              121
Loan_Tenure_Months         0
Interest_Rate_Percent      0
Credit_Score             121
Debt_To_Income_Ratio       0
Approval_Status            0
Default_Flag               0
Loan_Status                0
Customer_Rating            0
Risk_Category              0
dtype: int64

In [9]:
# Remove missing values

df = df.dropna(subset = ['Income','Employment_Type','Loan_Amount','Credit_Score'])

In [10]:
df.isnull().sum()

Loan_ID                  0
Application_Date         0
City                     0
Region                   0
Age                      0
Employment_Type          0
Income                   0
Loan_Amount              0
Loan_Tenure_Months       0
Interest_Rate_Percent    0
Credit_Score             0
Debt_To_Income_Ratio     0
Approval_Status          0
Default_Flag             0
Loan_Status              0
Customer_Rating          0
Risk_Category            0
dtype: int64

In [11]:
# Removing duplicates

df.drop_duplicates()

,Loan_ID,Application_Date,City,Region,Age,Employment_Type,Income,Loan_Amount,Loan_Tenure_Months,Interest_Rate_Percent,Credit_Score,Debt_To_Income_Ratio,Approval_Status,Default_Flag,Loan_Status,Customer_Rating,Risk_Category
0,LN102453,2023-08-13,Mumbai,West,43,Self-Employed,90322.0,980052.0,84,10.92,672.0,0.185,Approved,0,Active,4.1,Medium
1,LN100671,2024-11-26,Hyderabad,South,28,Salaried,32617.0,488350.0,54,9.99,698.0,0.345,Approved,0,Paid,4.6,Medium
3,LN100618,2023-04-07,Mumbai,West,33,Self-Employed,110760.0,1298938.0,59,8.36,730.0,0.243,Approved,0,Active,5.0,Low
4,LN100344,2023-05-30,Mumbai,West,37,Salaried,141338.0,1627058.0,110,10.14,767.0,0.161,Approved,0,Active,4.5,Low
5,LN102326,2023-06-11,Mumbai,West,37,Self-Employed,80818.0,646619.0,107,12.17,630.0,0.123,Rejected,0,rejected,5.0,high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2993,LN100146,2023-06-23,Chennai,South,39,Salaried,67540.0,1024534.0,93,12.14,722.0,0.252,Approved,0,Active,4.8,Low
2996,LN100826,2024-08-22,Chennai,South,39,Salaried,137421.0,1187769.0,80,9.84,736.0,0.148,Rejected,0,Rejected,4.9,Low
2997,LN101442,2024-06-02,Mumbai,West,35,Self-Employed,114418.0,1106424.0,106,9.76,642.0,0.136,approved,0,Active,4.4,High
2998,LN100843,2024-03-05,Delhi,North,31,Salaried,107985.0,1195475.0,106,7.84,625.0,0.145,Rejected,0,Rejected,4.4,High
2999,LN102624,2024-02-27,Mumbai,West,26,Self-Employed,41122.0,440398.0,53,14.00,662.0,0.272,Rejected,0,Rejected,5.0,Medium

In [ ]:
# Calculate Average

In [12]:
avg_income = df["Income"].mean()
print(avg_income)

84498.18399372303

In [ ]:
# Groupby category

In [13]:
# Average Loan Amount by City

avg_loan_city = df.groupby("City")["Loan_Amount"].mean()
print(avg_loan_city)

City
Bengaluru    9.346507e+05
Chennai      9.548683e+05
Delhi        8.826956e+05
Hyderabad    8.874481e+05
Mumbai       9.313021e+05
Pune         8.925738e+05
bengaluru    9.401372e+05
chennai      1.003675e+06
delhi        8.652358e+05
hyderabad    1.039661e+06
mumbai       9.061769e+05
pune         7.588863e+05
Name: Loan_Amount, dtype: float64

In [14]:
# Total Income by Region

total_income_region = df.groupby("Region")["Income"].sum()
print(total_income_region)

Region
North     39636505.0
South    101588160.0
West      74161206.0
Name: Income, dtype: float64

In [15]:
# Average Credit Score by Employment Type

avg_credit_emp = df.groupby("Employment_Type")["Credit_Score"].mean()
print(avg_credit_emp)

Employment_Type
Business         681.147410
Salaried         705.844291
Self-Employed    677.045455
business         666.000000
salaried         696.923077
self-employed    695.450000
Name: Credit_Score, dtype: float64

In [16]:
# Count of Loans by Approval Status

loan_count_approval = df.groupby("Approval_Status")["Loan_ID"].count()
print(loan_count_approval)

Approval_Status
Approved    1651
Rejected     820
approved      54
rejected      24
Name: Loan_ID, dtype: int64

In [17]:
# Average Income by Risk Category

avg_income_risk = df.groupby("Risk_Category")["Income"].mean()
print(avg_income_risk)

Risk_Category
High      78592.846570
Low       90305.911361
Medium    83101.433660
high      77330.454545
low       97211.227273
medium    86947.111111
Name: Income, dtype: float64