# Numpy

In [1]:
import numpy as np

In [2]:
# 1D Array

array_1d = np.array([5, 10, 15, 20, 25])
print("1D Array:", array_1d)

1D Array: [ 5 10 15 20 25]

In [3]:
# 2D Array

array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])
print("\n2D Array:\n", array_2d)

2D Array:
 [[1 2 3]
 [4 5 6]]

In [4]:
# 3. Mathematical Operations

print("\nAddition:", array_1d + 2)

print("Multiplication:", array_1d * 3)

print("Subtraction:", array_1d - 1)

print("Division:", array_1d / 2)

Addition: [ 7 12 17 22 27]
Multiplication: [15 30 45 60 75]
Subtraction: [ 4  9 14 19 24]
Division: [ 2.5  5.   7.5 10.  12.5]

In [5]:
# 4. Slicing Arrays

print("\nFirst 3 Elements:", array_1d[:3])
print("Last 2 Elements:", array_1d[-2:])

First 3 Elements: [ 5 10 15]
Last 2 Elements: [20 25]

In [6]:
# Change Values

array_1d[0] = 100
print("Updated 1D Array:", array_1d)

Updated 1D Array: [100  10  15  20  25]

In [7]:
array_2d[0, 1] = 50
print("Updated 2D Array:\n", array_2d)

Updated 2D Array:
 [[ 1 50  3]
 [ 4  5  6]]

In [8]:
# 5. Broadcasting (Add 10 to all elements)

broadcast_result = array_2d + 10
print("\nBroadcasting Result:\n", broadcast_result)

Broadcasting Result:
 [[11 60 13]
 [14 15 16]]

In [9]:
# 6. Statistical Calculations

print("\nMean:", np.mean(array_1d))

print("Sum:", np.sum(array_1d))

print("Maximum:", np.max(array_1d))

print("Minimum:", np.min(array_1d))

Mean: 34.0
Sum: 170
Maximum: 100
Minimum: 10

# Pandas

In [11]:
import pandas as pd

In [12]:
# 1. Create DataFrame from Dictionary

data = {
    "Name": ["Shravani", "Neha", "Atharv", "Sneha"],
    "Age": [21, 23, 22, 24],
    "Marks": [85, 90, 78, 88],
    "City": ["Pune", "Mumbai", "Pune", "Delhi"]
}

df = pd.DataFrame(data)
print("DataFrame from Dictionary:\n", df)

DataFrame from Dictionary:
        Name  Age  Marks    City
0  Shravani   21     85    Pune
1      Neha   23     90  Mumbai
2    Atharv   22     78    Pune
3     Sneha   24     88   Delhi

In [27]:
# 2.Load CSV dataset

df1 = pd.read_csv("C:\\Users\\Administrator\\Downloads\\Bank_Loan_Portfolio.csv")
print("\nCSV Data:\n", df1.head())

CSV Data:
     Loan_ID Application_Date       City Region  Age Employment_Type    Income  \
0  LN102453       2023-08-13     Mumbai   West   43   Self-Employed   90322.0
1  LN100671       2024-11-26  Hyderabad  South   28        Salaried   32617.0
2  LN100884       2024-03-07     Mumbai   West   34        Business   86468.0
3  LN100618       2023-04-07     Mumbai   West   33   Self-Employed  110760.0
4  LN100344       2023-05-30     Mumbai   West   37        Salaried  141338.0

   Loan_Amount  Loan_Tenure_Months  Interest_Rate_Percent  Credit_Score  \
0     980052.0                  84                  10.92         672.0
1     488350.0                  54                   9.99         698.0
2          NaN                  53                  11.56         709.0
3    1298938.0                  59                   8.36         730.0
4    1627058.0                 110                  10.14         767.0

   Debt_To_Income_Ratio Approval_Status  Default_Flag Loan_Status  \
0                 0.185        Approved             0      Active
1                 0.345        Approved             0        Paid
2                 0.422        Rejected             0    Rejected
3                 0.243        Approved             0      Active
4                 0.161        Approved             0      Active

   Customer_Rating Risk_Category
0              4.1        Medium
1              4.6        Medium
2              4.4        Medium
3              5.0           Low
4              4.5           Low

In [28]:
df1.head()

,Loan_ID,Application_Date,City,Region,Age,Employment_Type,Income,Loan_Amount,Loan_Tenure_Months,Interest_Rate_Percent,Credit_Score,Debt_To_Income_Ratio,Approval_Status,Default_Flag,Loan_Status,Customer_Rating,Risk_Category
0,LN102453,2023-08-13,Mumbai,West,43,Self-Employed,90322.0,980052.0,84,10.92,672.0,0.185,Approved,0,Active,4.1,Medium
1,LN100671,2024-11-26,Hyderabad,South,28,Salaried,32617.0,488350.0,54,9.99,698.0,0.345,Approved,0,Paid,4.6,Medium
2,LN100884,2024-03-07,Mumbai,West,34,Business,86468.0,NaN,53,11.56,709.0,0.422,Rejected,0,Rejected,4.4,Medium
3,LN100618,2023-04-07,Mumbai,West,33,Self-Employed,110760.0,1298938.0,59,8.36,730.0,0.243,Approved,0,Active,5.0,Low
4,LN100344,2023-05-30,Mumbai,West,37,Salaried,141338.0,1627058.0,110,10.14,767.0,0.161,Approved,0,Active,4.5,Low

In [29]:
df1.sample(5)

,Loan_ID,Application_Date,City,Region,Age,Employment_Type,Income,Loan_Amount,Loan_Tenure_Months,Interest_Rate_Percent,Credit_Score,Debt_To_Income_Ratio,Approval_Status,Default_Flag,Loan_Status,Customer_Rating,Risk_Category
1920,LN101802,2024-10-20,Mumbai,West,35,Salaried,55143.0,528439.0,56,10.18,743.0,0.216,Approved,0,Active,4.7,Low
2221,LN101562,2023-06-23,Pune,West,29,Self-Employed,38824.0,178675.0,52,11.66,657.0,0.113,Approved,0,Active,4.5,Medium
118,LN102427,2023-08-26,Bengaluru,South,38,Business,86408.0,876049.0,99,9.65,666.0,0.149,Rejected,0,Rejected,4.9,Medium
1251,LN101083,2023-11-18,Chennai,South,37,Salaried,76874.0,963619.0,109,9.13,726.0,0.170,Approved,0,Paid,5.0,Low
2251,LN100333,2023-10-29,Pune,West,36,Salaried,64403.0,794722.0,103,11.80,681.0,0.191,Approved,0,Active,5.0,Medium

In [30]:
# Getting the list of column names from the dataframe 

column_names_list = df1.columns.tolist()
print(column_names_list)

['Loan_ID', 'Application_Date', 'City', 'Region', 'Age', 'Employment_Type', 'Income', 'Loan_Amount', 'Loan_Tenure_Months', 'Interest_Rate_Percent', 'Credit_Score', 'Debt_To_Income_Ratio', 'Approval_Status', 'Default_Flag', 'Loan_Status', 'Customer_Rating', 'Risk_Category']

In [31]:
# Checking shape of the dataframe

df1.shape

(3000, 17)

In [32]:
# Checking datatypes of all columns in the dataframe
df1.dtypes

Loan_ID                   object
Application_Date          object
City                      object
Region                    object
Age                        int64
Employment_Type           object
Income                   float64
Loan_Amount              float64
Loan_Tenure_Months         int64
Interest_Rate_Percent    float64
Credit_Score             float64
Debt_To_Income_Ratio     float64
Approval_Status           object
Default_Flag               int64
Loan_Status               object
Customer_Rating          float64
Risk_Category             object
dtype: object

In [33]:
df1.isnull().sum()

Loan_ID                    0
Application_Date           0
City                       0
Region                     0
Age                        0
Employment_Type          120
Income                   120
Loan_Amount              121
Loan_Tenure_Months         0
Interest_Rate_Percent      0
Credit_Score             121
Debt_To_Income_Ratio       0
Approval_Status            0
Default_Flag               0
Loan_Status                0
Customer_Rating            0
Risk_Category              0
dtype: int64

In [35]:
# Remove missing values

df1 = df1.dropna(subset = ['Income','Employment_Type','Loan_Amount','Credit_Score'])

In [37]:
df1.isnull().sum()

Loan_ID                  0
Application_Date         0
City                     0
Region                   0
Age                      0
Employment_Type          0
Income                   0
Loan_Amount              0
Loan_Tenure_Months       0
Interest_Rate_Percent    0
Credit_Score             0
Debt_To_Income_Ratio     0
Approval_Status          0
Default_Flag             0
Loan_Status              0
Customer_Rating          0
Risk_Category            0
dtype: int64

In [38]:
df1.head()

,Loan_ID,Application_Date,City,Region,Age,Employment_Type,Income,Loan_Amount,Loan_Tenure_Months,Interest_Rate_Percent,Credit_Score,Debt_To_Income_Ratio,Approval_Status,Default_Flag,Loan_Status,Customer_Rating,Risk_Category
0,LN102453,2023-08-13,Mumbai,West,43,Self-Employed,90322.0,980052.0,84,10.92,672.0,0.185,Approved,0,Active,4.1,Medium
1,LN100671,2024-11-26,Hyderabad,South,28,Salaried,32617.0,488350.0,54,9.99,698.0,0.345,Approved,0,Paid,4.6,Medium
3,LN100618,2023-04-07,Mumbai,West,33,Self-Employed,110760.0,1298938.0,59,8.36,730.0,0.243,Approved,0,Active,5.0,Low
4,LN100344,2023-05-30,Mumbai,West,37,Salaried,141338.0,1627058.0,110,10.14,767.0,0.161,Approved,0,Active,4.5,Low
5,LN102326,2023-06-11,Mumbai,West,37,Self-Employed,80818.0,646619.0,107,12.17,630.0,0.123,Rejected,0,rejected,5.0,high

In [39]:
# Average Loan Amount by City

avg_loan_city = df1.groupby("City")["Loan_Amount"].mean()
print(avg_loan_city)

City
Bengaluru    9.346507e+05
Chennai      9.548683e+05
Delhi        8.826956e+05
Hyderabad    8.874481e+05
Mumbai       9.313021e+05
Pune         8.925738e+05
bengaluru    9.401372e+05
chennai      1.003675e+06
delhi        8.652358e+05
hyderabad    1.039661e+06
mumbai       9.061769e+05
pune         7.588863e+05
Name: Loan_Amount, dtype: float64

In [41]:
# Total Income by Region

total_income_region = df1.groupby("Region")["Income"].sum()
print(total_income_region)

Region
North     39636505.0
South    101588160.0
West      74161206.0
Name: Income, dtype: float64

In [43]:
# Average Credit Score by Employment Type

avg_credit_emp = df1.groupby("Employment_Type")["Credit_Score"].mean()
print(avg_credit_emp)

Employment_Type
Business         681.147410
Salaried         705.844291
Self-Employed    677.045455
business         666.000000
salaried         696.923077
self-employed    695.450000
Name: Credit_Score, dtype: float64

In [44]:
# Count of Loans by Approval Status

loan_count_approval = df1.groupby("Approval_Status")["Loan_ID"].count()
print(loan_count_approval)

Approval_Status
Approved    1651
Rejected     820
approved      54
rejected      24
Name: Loan_ID, dtype: int64

In [45]:
# Average Income by Risk Category

avg_income_risk = df1.groupby("Risk_Category")["Income"].mean()
print(avg_income_risk)

Risk_Category
High      78592.846570
Low       90305.911361
Medium    83101.433660
high      77330.454545
low       97211.227273
medium    86947.111111
Name: Income, dtype: float64